### ISSUE TITLE
Other Distribution History Date

### ISSUE THREAD

**Issue by djstrikanova** [effectai/effect-dao#105]
Add a Date for the distributions of the Effect Network Fee Distributions, primarily so users know it's in the past.

**Comment by jeisses** [comment]
Instead of figuring out the exact date of the distributions, I think it's also acceptable if we display a check mark icon ( :heavy_check_mark: ) and the year `2021` at the right in the distribution table.

**Comment by MiggySmallz** [comment]
![Image](https://user-images.githubusercontent.com/22913608/195900605-ccbc7358-7c86-47b4-b28f-e2b014e4e4ed.png)

Something like this maybe?

**Comment by jeisses** [comment]
@MiggySmallz That looks clear to me :relaxed:
