### ISSUE TITLE
Prompt for selecting wallet when account is remembered.

### ISSUE THREAD

**Issue by djstrikanova** [effectai/effect-dao#111]
When I load the Effect Dashboard, it remembers my wallet but it still prompts me to select a wallet.

**Comment by jabbarn** [comment]
Hi @djstrikanova do you know how to reproduce it? I can remember I had this issue aswell but when I login into the effect dashboard, close the browser and reopen it back to the dashboard, it doesnt show a wallet prompt on any page.

**Comment by djstrikanova** [comment]
Maybe it's just a Brave browser thing then.

**Comment by jeisses** [comment]
Closing this for now, please re-open if this is still happening
