### ISSUE TITLE
Opengraph Metadata

### ISSUE THREAD

**Issue by djstrikanova** [effectai/effect-dao#85]
Embeds don't look nice, would be nice to have opengraph metadata available on all the dashboard pages and proposal pages so things look nice when posting a link in social media.

**Comment by jeisses** [comment]
This issue is partially fixed. There is generic OpenGraph metadata for links to the DAO, but not specific for proposals yet.
![image](https://user-images.githubusercontent.com/1128863/134930478-f4647a94-47ae-450a-b176-d2bce491f024.png)
