### ISSUE TITLE
Vote Measurements better look

### ISSUE THREAD

**Issue by djstrikanova** [effectai/effect-dao#92]
Discussed in DAO talk
Proposals List Page
200k vs 2000k
200k vs 2m

Basically make it look more consistent and easier to understand at a glance. Stop overflow of votes to second line

**Comment by jeisses** [comment]
Thanks for making the issue.
This might have already been solved in this PR: https://github.com/effectai/effect-dashboard/pull/91
Which is deployed at https://dao.effect.network/proposals

Does it solve the items you're mentioning?

**Comment by djstrikanova** [comment]
Well it solves it in a way, but not in a way I like. It no longer shows the Abs/Y/N votes on the proposal list, but I liked it being there since you can look at the status of all active proposals at a glance.

When looking at proposal pages, once votes go over a million "M" notation is used but there was discussion that it's better to just use "K" only. So instead of 3.5 it would be 3,500K.

**Comment by jeisses** [comment]
I think this has been resolved by now, as the display is updated and we are also showing the percentage.
